FROM node:16-alpine

# Usamos el nombre de tu carpeta real
WORKDIR /vue-frontend

# Copiar archivos de configuración primero
COPY package*.json .
COPY vite.config.ts .

# Instalar dependencias
RUN npm install

# Copiar código fuente
COPY . .

# Puerto de Vite
EXPOSE 5174

# Comando para desarrollo
CMD ["npm", "run", "dev"]